### ISSUE TITLE
Error on windows for virutal midi port

### ISSUE THREAD

**Issue by MegaMech** [dinchak/node-easymidi#3] opened 2018-05-17 20:27 UTC
I am getting the following error message:
MidiOutWinMM::openPort: error creating Windows MM MIDI output port.

Any ideas how to make the virtual midi port work?

**Comment by Bholtland** [comment] 2018-06-10 10:43
Yeah the issue is coming from the "midi" package. I hope someone can find a fix for this. It works fine on Mac

**Comment by dinchak** [comment] 2018-06-10 16:45
i upgraded the midi package to the latest version, let me know if that helps! other than that i'm not sure how to fix it, sorry

**Comment by Bholtland** [comment] 2018-06-10 18:29
Thanks! I will try it when i'm home. I've done some research though. And it seems that RtMidi is unable to open virtual ports on Windows by default. Sources say it should be possible by installing a separate driver. I'll share them whenever i can. I don't have them at hand right now. I'm not sure of this is Windows 10 specific.

**Comment by dinchak** [comment] 2018-06-10 18:35
thanks for taking the time to look into it!! you could be right about no virtual port support in windows, that would be unfortunate

**Comment by dinchak** [comment] 2018-11-03 15:13
closing for now, hopefully this can be resolved someday

**Closed as completed by dinchak** 2018-11-03 15:13 UTC
